/**
 * This file was automatically generated by the Mule Development Kit
 */

package com.fom.nettypublisher;

import org.mule.DefaultMuleMessage;
import org.mule.api.MuleEvent;
import org.mule.api.MuleMessage;
import org.mule.api.client.MuleClient;
import org.mule.construct.Flow;
import org.mule.tck.junit4.FunctionalTestCase;
import org.mule.transport.NullPayload;

import org.junit.Assert;
import org.junit.Test;

public class NettyPublisherConnectorTest extends FunctionalTestCase
{
    protected static final String PAYLOAD = "some data\r\n";
    @Override
    protected String getConfigResources()
    {
        return "mule-config.xml, test-mule-config.xml";
    }

    protected class RunTcpTest extends Thread
    {
        private String result;
        public void run()
        {
            try
            {
                MuleClient client = muleContext.getClient();
                MuleMessage response = client.send("tcp://localhost:8091?connector=tcpConnector", new DefaultMuleMessage("", muleContext), 10000);
                result = response.getPayloadAsString();
                logger.info("*******************" + result);
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
        
        public String getResult()
        {
            return result;
        }
    }

    @Test
    public void testFlow() throws Exception
    {
        RunTcpTest t1 = new RunTcpTest();
        
        Thread.sleep(1000);
        t1.start();
        Thread.sleep(1000);
        
        runFlowAndExpect("testFlow", NullPayload.getInstance());
        
        t1.join();
        Assert.assertEquals(PAYLOAD, t1.getResult());
    }

    /**
     * Run the flow specified by name and assert equality on the expected output
     * 
     * @param flowName The name of the flow to run
     * @param expect The expected output
     */
    protected <T> void runFlowAndExpect(String flowName, T expect) throws Exception
    {
        Flow flow = lookupFlowConstruct(flowName);
        MuleEvent event = getTestEvent(PAYLOAD);
        MuleEvent responseEvent = flow.process(event);

        Assert.assertEquals(expect, responseEvent.getMessage().getPayload());
    }

    /**
     * Run the flow specified by name using the specified payload and assert equality
     * on the expected output
     * 
     * @param flowName The name of the flow to run
     * @param expect The expected output
     * @param payload The payload of the input event
     */
    protected <T, U> void runFlowWithPayloadAndExpect(String flowName, T expect, U payload) throws Exception
    {
        Flow flow = lookupFlowConstruct(flowName);
        MuleEvent event = getTestEvent(payload);
        MuleEvent responseEvent = flow.process(event);

        Assert.assertEquals(expect, responseEvent.getMessage().getPayload());
    }

    /**
     * Retrieve a flow by name from the registry
     * 
     * @param name Name of the flow to retrieve
     */
    protected Flow lookupFlowConstruct(String name)
    {
        return (Flow) muleContext.getRegistry().lookupFlowConstruct(name);
    }
}
